---
title: "EDA Time Series Plots"
author: "Weijia Bao"
date: "10/03/2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE,
                      message = FALSE, cache = FALSE)
```

```{r warning=FALSE}
library(RColorBrewer)
library(ggplot2)
library(tidyverse)
library(lubridate)
library(plotly)
```

```{r load data and preprocess}
Shooting_data <- read.csv("NYPD_Shooting_modified1.csv")
Shooting_data$Numeric_time = as.numeric(hms(Shooting_data$OCCUR_TIME))/60
```

## Time Series

+ stat plot
```{r}
# Change the time format 
Shooting_data$OCCUR_DATE<- format(as.Date(Shooting_data$OCCUR_DATE, format = "%m/%d/%Y"), "%Y-%m-%d")
Shooting_data$OCCUR_DATE <- as.Date(Shooting_data$OCCUR_DATE)

# overview
overall_data<- Shooting_data %>% group_by(OCCUR_DATE) %>% summarize(count = n())
ggplot(overall_data, aes(OCCUR_DATE, count))+
  geom_line()+
  ggtitle("Overview Shooting Counts from 2006-2018")

######################################### Year ######################################### 
# Shooting counts by year
Shooting_data$OCCUR_YEAR <- year(Shooting_data$OCCUR_DATE)

year_data <- Shooting_data %>% group_by(OCCUR_YEAR) %>% summarize(count = n())
ggplot(year_data, aes(OCCUR_YEAR, count))+
  geom_point()+
  geom_line(color = "grey50")+
  ggtitle("Shooting Counts from 2006-2018 by year")+
  xlab("")+
  geom_label(aes(label = count))

# year shooting by boro
year_boro <- Shooting_data %>% group_by(OCCUR_YEAR, BORO) %>%
   summarize(count = n())

#year_boro <- Shooting_data %>% group_by(Month = floor_date(OCCUR_DATE, "month"), BORO) %>%
   #summarize(count = n())

ggplot(year_boro, aes(OCCUR_YEAR, count, color = BORO))+
  geom_point()+
  geom_line(aes(group= BORO))+
  ggtitle("Shootings counts by boro/year")

# year shooting by murder
year_murder <- Shooting_data %>% group_by(OCCUR_YEAR, STATISTICAL_MURDER_FLAG) %>%
   summarize(count = n())
ggplot(year_murder, aes(OCCUR_YEAR, count, color = STATISTICAL_MURDER_FLAG))+
  geom_point()+
  geom_line(aes(group= STATISTICAL_MURDER_FLAG))+
  ggtitle("Shootings counts by murder/year")

######################################### Season ######################################### 
Shooting_data$OCCUR_YEAR<-as.factor(Shooting_data$OCCUR_YEAR)
Shooting_data$OCCUR_SEASON<-quarters(Shooting_data$OCCUR_DATE)
# season by year
season_year <- Shooting_data %>% group_by(OCCUR_SEASON, OCCUR_YEAR) %>%
  summarize(count = n())
ggplot(season_year, aes(OCCUR_SEASON, count, color = OCCUR_YEAR))+
  geom_line(aes(group= OCCUR_YEAR))+
  ggtitle("season/year")

######################################### Month & Weekday ##################################
Shooting_data$OCCUR_MONTH<-months(Shooting_data$OCCUR_DATE)
Shooting_data$OCCUR_WEEKDAY <-wday(Shooting_data$OCCUR_DATE, label = TRUE)
# month by weekday
month_weekday <- Shooting_data %>% group_by(OCCUR_MONTH, OCCUR_WEEKDAY) %>%
  summarize(count = n()) 
# facets
ggplot(month_weekday, aes(OCCUR_MONTH, count))+
         geom_line(aes(group= OCCUR_WEEKDAY))+
         facet_grid(OCCUR_WEEKDAY~.)+
  geom_bar(stat = "identity", fill="aliceblue", alpha= 0.9)+
  ggtitle("month/weekday")

gg<-ggplot(overall_data, aes(OCCUR_DATE, count))+
         geom_line()+
         facet_grid(.~wday(overall_data$OCCUR_DATE, label = TRUE))+
  ggtitle("year/weekday")
ggplotly(gg)
############################# Different pattern for Christmas Week ###########################
# Take 2017 for example
# Label by day of month
christmas_2017 <- Shooting_data %>%
  filter(OCCUR_DATE >= as.Date("2017-12-20") & 
           OCCUR_DATE <= as.Date("2018-01-03")) %>%
  group_by(OCCUR_DATE) %>%
  summarize(count = n())

g <- ggplot(christmas_2017, aes(OCCUR_DATE, count)) +
  geom_label(aes(label = wday(OCCUR_DATE, label = TRUE))) +
  geom_line(color = "cornflowerblue") +
  scale_x_date(date_labels = "%b\n%d",
  date_breaks = "1 day")
g
# Highlight the abnormality
start <- as.Date("2017-12-24")
end <- as.Date("2017-12-27")
g+annotate("rect", xmin = start, xmax = end,
             ymin = -Inf, ymax = Inf, fill = "green",
             alpha = .2) +
    annotate("text", x = end + 2,
             y = 10, label = "Dec 24 - Dec 27",
             color = "green", hjust = 0) +
    theme_classic()

############################# Independence Day ################################################
# Take 2017 for example
year2017 <- Shooting_data %>%
  filter(OCCUR_DATE >= as.Date("2017-01-01") & 
           OCCUR_DATE <= as.Date("2017-12-31")) %>%
  group_by(OCCUR_DATE) %>%
  summarize(count = n())
ggplot(year2017, aes(OCCUR_DATE, count))  +
  geom_line() +
  geom_vline(xintercept = ymd("2017-07-04"), color = "blue", size =1)+
  scale_x_date(date_labels = "%b %y")+
    theme_grey(16)
```
```{r}
###################################### Event ######################################### 
###################################### Event ######################################### 
###################################### Event ######################################### 
library(ggplot2)
library(ggpubr)
eventimage = function (x, i){# x is the holiday dataframe, i is the year
  data <- Shooting_data %>%
    filter(OCCUR_DATE >= as.Date(x[i, ]$start_date, format = "%Y-%m-%d")&
             OCCUR_DATE <= as.Date(x[i, ]$end_date, format = "%Y-%m-%d")) %>%
    group_by(OCCUR_DATE) %>%
    summarize(count = n())
  g <- ggplot(data, aes(OCCUR_DATE, count)) +
  geom_label(aes(label = wday(OCCUR_DATE, label = TRUE))) +
  geom_line(color = "cornflowerblue") +
  xlab("")+
  scale_x_date(date_labels = "%b\n%d",
  date_breaks = "1 day")
  
  start <- as.Date(x[i, ]$beginning, format = "%Y-%m-%d")
  end <- as.Date(x[i, ]$ending, format = "%Y-%m-%d")
  g+annotate("rect", xmin = start, xmax = end,
             ymin = -Inf, ymax = Inf, fill = "green",
             alpha = .2) +
    annotate("text", x = end + 1,
             y = 10, label = paste(x[i, ]$label, ", ", i+2005),
             color = "green", hjust = 0) +
    theme_classic()
}

# example of a single input
eventimage(Independence_day, 1)
# x is the holiday dataframe
# i is the #row from 1-13, each representing year 2006(i=1) to 2018(i=13)

christmas<-data.frame(
  "start_date" = c(
  "2006-12-20","2007-12-20","2008-12-20","2009-12-20","2010-12-20",
  "2011-12-20","2012-12-20","2013-12-20","2014-12-20",
  "2015-12-20","2016-12-20","2017-12-20","2018-12-20"),
  "end_date" = c(
  "2007-01-03","2008-01-03","2009-01-03","2010-01-03","2011-01-03",
  "2012-01-03","2013-01-03","2014-01-03","2015-01-03",
  "2016-01-03","2017-01-03","2018-01-03","2019-01-03"), 
  "beginning" = c(
  "2006-12-24","2007-12-24","2008-12-24","2009-12-24","2010-12-24",
  "2011-12-24","2012-12-24","2013-12-24","2014-12-24",
  "2015-12-24","2016-12-24","2017-12-24", "2019-12-24"),
  "ending" = c(
  "2006-12-27", "2007-12-27","2008-12-27","2009-12-27","2010-12-27",
  "2011-12-27","2012-12-27","2013-12-27","2014-12-27",
  "2015-12-27","2016-12-27","2017-12-27","2018-12-27"),
  "label" = rep("Dec 24 - Dec 27",13)
  )

new_year<-data.frame(
  "start_date" = c(
  "2006-12-22","2007-12-22","2008-12-22","2009-12-22","2010-12-22",
  "2011-12-22","2012-12-22","2013-12-22","2014-12-22",
  "2015-12-22","2016-12-22","2017-12-22","2018-12-22"),
  "end_date" = c(
  "2007-01-10","2008-01-10","2009-01-10","2010-01-10","2011-01-10",
  "2012-01-10","2013-01-10","2014-01-10","2015-01-10",
  "2016-01-10","2017-01-10","2018-01-10","2019-01-10"), 
  "beginning" = c(
  "2006-12-31","2007-12-31","2008-12-31","2009-12-31","2010-12-31",
  "2011-12-31","2012-12-31","2013-12-31","2014-12-31",
  "2015-12-31","2016-12-31","2017-12-31", "2018-12-28"),
  "ending" = c(
  "2007-01-03", "2008-01-03","2009-01-03","2010-01-03","2011-01-03",
  "2012-01-03","2013-01-03","2014-01-03","2015-01-03",
  "2016-01-03","2017-01-03","2018-01-03", "2019-01-03"),
  "label" = rep("Dec 31 - Jan 03",13)
  )

Independence_day<-data.frame(
  "start_date" = c(
  "2006-06-30","2007-06-30","2008-06-30","2009-06-30","2010-06-30",
  "2011-06-30","2012-06-30","2013-06-30","2014-06-30",
  "2015-06-30","2016-06-30","2017-06-30","2018-06-30"),
  "end_date" = c(
  "2006-07-13","2007-07-13","2008-07-13","2009-07-13","2010-07-13",
  "2011-07-13","2012-07-13","2013-07-13","2014-07-13",
  "2015-07-13","2016-07-13","2017-07-13","2018-07-13"), 
  "beginning" = c(
  "2006-07-03","2007-07-03","2008-07-03","2009-07-03","2010-07-03",
  "2011-07-03","2012-07-03","2013-07-03","2014-07-03",
  "2015-07-03","2016-07-03","2017-07-03", "2019-07-03"),
  "ending" = c(
  "2006-07-06", "2007-07-06","2008-07-06","2009-07-06","2010-07-06",
  "2011-07-06","2012-07-06","2013-07-06","2014-07-06",
  "2015-07-06","2016-07-06","2017-07-06","2018-07-06"),
  "label" = rep("Jul 03 - Jul 06", 13)
  )

Halloween<-data.frame(
  "start_date" = c(
  "2006-10-25","2007-10-25","2008-10-25","2009-10-25","2010-10-25",
  "2011-10-25","2012-10-25","2013-10-25","2014-10-25",
  "2015-10-25","2016-10-25","2017-10-25","2018-10-25"),
  "end_date" = c(
  "2006-11-03","2007-11-03","2008-11-03","2009-11-03","2010-11-03",
  "2011-11-03","2012-11-03","2013-11-03","2014-11-03",
  "2015-11-03","2016-11-03","2017-11-03","2018-11-03"), 
  "beginning" = c(
  "2006-10-30","2007-10-30","2008-10-30","2009-10-30","2010-10-30",
  "2011-10-30","2012-10-30","2013-10-30","2014-10-30",
  "2015-10-30","2016-10-30","2017-10-30", "2019-10-30"),
  "ending" = c(
  "2006-11-02", "2007-11-02","2008-11-02","2009-11-02","2010-11-02",
  "2011-11-02","2012-11-02","2013-11-02","2014-11-02",
  "2015-11-02","2016-11-02","2017-11-02","2018-11-02"),
  "label" = rep("Oct 30 - Nov 02", 13)
  )


######################################### Year ######################################### 
# Shooting counts by year
Shooting_data$OCCUR_YEAR <- year(Shooting_data$OCCUR_DATE)

year_data <- Shooting_data %>% group_by(OCCUR_YEAR) %>% summarize(count = n())
ggplot(year_data, aes(OCCUR_YEAR, count))+
  geom_point()+
  geom_line(color = "grey50")+
  ggtitle("Shooting Counts from 2006-2018 by year")+
  xlab("")+
  geom_label(aes(label = count))

######################################### Season ######################################### 
Shooting_data$Year<-as.factor(Shooting_data$OCCUR_YEAR)
Shooting_data$OCCUR_SEASON<-quarters(Shooting_data$OCCUR_DATE)
# season by year
season_year <- Shooting_data %>% group_by(OCCUR_SEASON, Year) %>%
  summarize(count = n())
ggplot(season_year, aes(OCCUR_SEASON, count, color = Year))+
  geom_line(aes(group= Year), line = 2)+
  ggtitle("Shooting Counts by season/year")+
  xlab("Season")+
  guides(fill = guide_legend(title = "Year"))

# year shooting by boro
year_boro <- Shooting_data %>% group_by(Year, BORO) %>%
   summarize(count = n())

ggplot(year_boro, aes(Year, count, color = BORO))+
  geom_point()+
  geom_line(aes(group= BORO))+
  xlab("")+
  ggtitle("Shootings Counts by boro/year")

# year shooting by murder
Shooting_data <- Shooting_data %>% rename(Murder = STATISTICAL_MURDER_FLAG)
year_murder <- Shooting_data %>% group_by(Year, Murder) %>%
   summarize(count = n())
ggplot(year_murder, aes(Year, count, color = Murder))+
  geom_point()+
  geom_line(aes(group= Murder))+
  xlab("")+
  ggtitle("Shootings Counts by murder/year")
```  


```{r}
# year shooting by boro
year_boro <- Shooting_data %>% group_by(OCCUR_YEAR, BORO) %>%
   summarize(count = n())

boro_overall <- function(x, boro){
year_boro <- Shooting_data %>% group_by(OCCUR_YEAR, BORO) %>%
   summarize(count = n())
   ggplot(year_boro %>% filter(BORO == x), aes(OCCUR_YEAR, count))+
  geom_point()+
  geom_line(aes(group= BORO))+
  ggtitle(paste("Shootings counts by year in", boro))+
  xlab("")
}

# example
boro_overall(x= "BRONX", boro ="BRONX")
# input x is the boro name
```




```{r}
# Needed plots
######################################### OVERVIEW ######################################### 

######################################### Year ######################################### 
# Shooting counts by year
overall_data<- Shooting_data %>% group_by(OCCUR_DATE) %>% summarize(count = n())
Shooting_data$OCCUR_YEAR <- year(Shooting_data$OCCUR_DATE)

year_data <- Shooting_data %>% group_by(OCCUR_YEAR) %>% summarize(count = n())
ggplot(year_data, aes(OCCUR_YEAR, count))+
  geom_point()+
  geom_line(color = "grey50")+
  ggtitle("Shooting Counts from 2006-2018 by year")

# year shooting by boro
year_boro <- Shooting_data %>% group_by(OCCUR_YEAR, BORO) %>%
   summarize(count = n())

gg<-ggplot(overall_data, aes(OCCUR_DATE, count))+
         geom_line()+
         facet_grid(.~wday(overall_data$OCCUR_DATE, label = TRUE))+
  ggtitle("year/weekday")
ggplotly(gg)

######################################### Season ######################################### 
Shooting_data$OCCUR_YEAR<-as.factor(Shooting_data$OCCUR_YEAR)
Shooting_data$OCCUR_SEASON<-quarters(Shooting_data$OCCUR_DATE)
# season by year
season_year <- Shooting_data %>% group_by(OCCUR_SEASON, OCCUR_YEAR) %>%
  summarize(count = n())
g <- ggplot(season_year, aes(OCCUR_SEASON, count, color = OCCUR_YEAR)) +
  geom_line(aes(group = OCCUR_YEAR)) +
  ggtitle("season/year")
ggplotly(g)

######################################### Month & Weekday ##################################
Shooting_data$OCCUR_MONTH<-months(Shooting_data$OCCUR_DATE)
#year_data$OCCUR_YEAR <- as.factor(year_data$OCCUR_YEAR)
Shooting_data$OCCUR_WEEKDAY <-wday(Shooting_data$OCCUR_DATE, label = TRUE)
overall_data$OCCUR_YEAR <- year(overall_data$OCCUR_DATE)
overall_data$weekday<- wday(overall_data$OCCUR_DATE, label = TRUE)
overall <- overall_data %>% 
  group_by(OCCUR_YEAR, weekday) %>%
  summarize(count = n())
# facets
ggplot(overall, aes(OCCUR_YEAR, count))+
  geom_point()+
         geom_line(aes(group = OCCUR_YEAR))+
         facet_grid(.~weekday)+
  ggtitle("year/weekday")+
  ylim(35, 53)

library(rio)
export(Shooting_data, "Shooting_data.Rdata")
```

